plugins {
    id 'java'
    id 'com.gradleup.shadow' version '8.3.6'
}

group = 'com.nocticraft'
version = '2.0.2'

repositories {
    mavenCentral()
    maven {
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'
    }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.20.1-R0.1-SNAPSHOT'
    implementation 'com.google.code.gson:gson:2.13.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

processResources {
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

jar {
    enabled = false
}

shadowJar {
    destinationDirectory.set(file('build/jars'))
    archiveFileName = "WooStoreLink-mc1.20-26.3-${project.version}.jar"
    relocate 'com.google.gson', 'com.nocticraft.woostorelink.libs.gson'
    minimize()
}

build {
    dependsOn shadowJar
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

tasks.withType(ProcessResources).configureEach {
    filteringCharset = 'UTF-8'
}
