# MySQL Database Settings
mysql:
  host: localhost
  port: 3306
  database: database-here
  user: user-here
  password: password-here

# Language: en (default), es (Spanish)
language: en

# How long transaction logs should be kept (in days)
log-file: deliveries.log
log-retention-days: 30  # 1 month

# How often to check for pending deliveries (in minutes)
check-interval-minutes: 1

# Products mapping: WooCommerce product name => Minecraft actions
products:
  test:
    items:
      - minecraft:dirt 5
    commands:
      - "say Thank you for your purchase, {player}!"
      - "title {player} title {\"text\":\"Purchase Complete!\",\"color\":\"gold\"}"

  diamond:
    commands:
      - "gamemode creative {player}"
