name: WooStoreLink
version: ${version}
main: com.nocticraft.woostorelink.WooStoreLink
api-version: 1.20
author: MrDinoCarlos
website: https://nocticraft.com
discord: https://discord.gg/ddyfucfZpy

commands:
  wsl:
    description: WooStoreLink management command
    usage: /wsl [help|reload|check|checkplayer|status]
    permission: ""
    permission-message: You do not have permission to use this command.

permissions:
  woostorelink.admin:
    description: Full access to WooStoreLink commands
    default: op
    children:
      woostorelink.reload: true
      woostorelink.check: true
      woostorelink.check.others: true
      woostorelink.status: true
      woostorelink.help: true

  woostorelink.reload:
    description: Allows /wsl reload
    default: op

  woostorelink.check:
    description: Allows /wsl check
    default: true

  woostorelink.check.others:
    description: Allows /wsl checkplayer <player>
    default: op

  woostorelink.status:
    description: Allows /wsl status
    default: true

  woostorelink.help:
    description: Allows /wsl help
    default: true

  woostorelink.wp-link:
    description: Allows /wsl wp-link
    default: true

  woostorelink.wp-verify:
    description: Allows /wsl wp-verify
    default: true

