name: WooStoreLink
version: ${version}
main: com.nocticraft.woostorelink.WooStoreLink
api-version: 1.20
description: WooCommerce delivery bridge for Minecraft 1.20.x, 1.21.x and 1.26.x.
author: MrDinoCarlos
website: https://mrdino.es
discord: https://discord.gg/ddyfucfZpy

commands:
  wsl:
    description: WooStoreLink management command
    usage: /wsl [menu|help|reload|check|checkplayer|status|wp-link|wp-verify|achievements]
    permission: ""
    permission-message: You do not have permission to use this command.

permissions:
  woostorelink.reload:
    description: Allows /wsl reload
    default: op

  woostorelink.check:
    description: Allows /wsl check
    default: true

  woostorelink.check.others:
    description: Allows /wsl checkplayer <player>
    default: op

  woostorelink.status:
    description: Allows /wsl status
    default: true

  woostorelink.wp-link:
    description: Allows /wsl wp-link <email>
    default: true

  woostorelink.wp-verify:
    description: Allows /wsl wp-verify <code>
    default: true

  woostorelink.achievements:
    description: View your achievement progress.
    default: true

  woostorelink.achievements.others:
    description: View achievement progress of other players.
    default: op
