name: WooStoreLink
version: ${version}
main: com.nocticraft.woostorelink.WooStoreLink
api-version: 1.20
author: MrDinoCarlos

commands:
  deliveries:
    description: Commands for store product deliveries
    usage: /deliveries <reload|check|log>
    permission: woostorelink.admin
    permission-message: You do not have permission to use this command.

